title: Typographi
description: :)
footer_text: Copyright 2021 Emma Pettengell
header_feature_image: ../uploads/moussaka.jpg
header_text: My Dream Blog
header_text_color: "#ffffff"
bannerheight: 20vmax
navbarheight: 55px
logo: /uploads/logo.jpg
favicon: /uploads/favicon.ico
gridlayout: false
fixednavbar: false
upzoom: true
