title: Type Face
description: :)
footer_text: Copyright 2021 Emma Pettengell
header_feature_image: ../uploads/typography-est.-2001-4.png
header_text: :)
header_text_color: "#ffffff"
bannerheight: 20vmax
navbarheight: 55px
logo: ../uploads/green-and-white-deer-stags-american-football-logo.png
favicon: /uploads/favicon.ico
gridlayout: false
fixednavbar: true
upzoom: true
